# Generated by Django 6.0 on 2025-12-20 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_post_postmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published')], default='Draft', max_length=10),
        ),
    ]
